version: '3.8'
services:
  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Welcome4$
      POSTGRES_DB: DataWarehouseX
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/etc/postgresql/work
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
volumes:
  pg-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /work